# Generated by Django 6.0.6 on 2026-06-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=20)),
                ('descripcion', models.TextField()),
                ('foto', models.URLField(blank=True, default='')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], default='Disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='adopciones.fundacion')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
