# Generated by Django 6.0.6 on 2026-06-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_solicitudadopcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='adopciones.fundacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Rescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_encontrado', models.CharField(max_length=255)),
                ('fecha_rescate', models.DateField()),
                ('estado_salud', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rescate', to='adopciones.mascota')),
            ],
            options={
                'ordering': ['-fecha_rescate'],
            },
        ),
    ]
